apiVersion: v1
kind: Service
metadata:
  labels:
    app: swath
  name: swath-lb
  namespace: swath
spec:
  selector:
    app: swath
  ports:
    - name: 80-9009 
      protocol: TCP
      port: 80
      targetPort: 9009