apiVersion: v1
kind: Service
metadata:
  labels:
    app: swath
  name: swath-lb
  namespace: swath
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: swath
  ports:
    - name: 80-9009 
      protocol: TCP
      port: 80
      targetPort: 9009